version: '3.8'
services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - '5678:5678'
    environment:
      - WEBHOOK_URL=http://localhost:5678
      - DB_TYPE=sqlite
      - GENERIC_TIMEZONE=Europe/Madrid
    volumes:
      - ./:/home/node/.n8n
    restart: unless-stopped
